@startuml
start
:Accept http POST request from CRSP;
 note right
            Data from CRSP:
            * transaction
            * network sub-map
        end note
:Read rule config from config DB;
 note right
            Required Parameter:
            * Rule ID
            * Rule CFG
        end note
if (Rule config is found & Rule config is valid) then (yes)
  if (Historical transactions are found) then (yes)
   : determine rule result;
  else (no)
   : Return ruleResult as false;
   stop
  endif
else (no)
  : Return ruleResult as false and Log the error;
  stop
endif
:Submit rule result to the typology processor;
note right
    Rule output payload includes:
    * Rule Result
    * Network sub-map
    * Original transaction data;
end note
stop
@enduml
