@startuml
start
:Accept http POST request from CRSP;
note right
    Data from CRSP:
    * Pacs 002 transaction
    * network sub-map
end note
:Read rule config from config DB;
note right
    Required Parameter:
    * Rule ID
    * Rule CFG
end note
if (Rule config is found & Rule config is valid) then (yes)
    if (Historical transactions are found no creditor in the current transaction ) then (yes)
        if (The creditor in the current transaction has successfully made any payments)
        else (no)
            : Return ruleResult as false;
            note right
                ruleResult:
                * "id": "001@1.1.0",
                * "cfg": "1.0.0",
                * "subRuleRef": ".00",
                * "result": false,
                * "reason": "No verifiable prior creditor account activity detected"
            end note
            stop
        endif

        :Compare the time since oldest transaction
        between the query results and the current transaction through the
        creation date time information with the time-bands;
        : determine rule result;
    else (no)
        : Return ruleResult as false;
        stop
    endif
else (no)
    : Return ruleResult as false and Log the error;
    stop
endif
:Submit rule result to the typology processor;
note right
    Rule output payload includes:
    * Rule Result
    * Network sub-map
    * Original transaction data;
end note
stop
@enduml
